server:
  port: 80
certificate:
  server:
    event-url: "${EVENT_URL:https://ieeeihuserres.org}"
    participants-file: "/srv/ieee/event/participants.csv"
    certificate-template: "/srv/ieee/event/certificate.pdf"
    theming:
      font-size: 40
      color:
        red: 37
        green: 24
        blue: 80
      text-coordinates:
        x: 420
        y: 330
        rotation: 0
