server:
  port: 80
spring:
  devtools:
    add-properties: false
certificate:
  server:
    event-url: "https://ieeeihuserres.org"
    participants-file: "/srv/ieee/event/participants.csv"
    certificate-template: "/srv/ieee/event/certificate.pdf"
    theming:
      font-size: 40
      color:
        red: 37
        green: 24
        blue: 80
      text-coordinates:
        x: 400
        y: 310
        rotation: 0